clc; clear;
filename = "./example_data.xlsx";
paradigms = ["1pulse", "80pps-2pulses", "80pps-4pulses"];
response_durations = [0.98, 0.98, 0.98];
membrane_potential_filters.firdifferentiator.order = 10;
membrane_potential_filters.firdifferentiator.Fpass = 100;
membrane_potential_filters.firdifferentiator.Fstop = 120;
membrane_potential_filters.firlowpass.order = 10;
membrane_potential_filters.firlowpass.Fpass = 50;
membrane_potential_filters.firlowpass.Fstop = 60;
membrane_current_filters.firlowpass.order = 10;
membrane_current_filters.firlowpass.Fpass = 100;
membrane_current_filters.firlowpass.Fstop = 120;
ds = WholeCellRecordingV2(filename, paradigms, response_durations, membrane_potential_filters, membrane_current_filters);
ds = ds.call();
da = ds.plot_estimations();