clc; clear;
filename = "./example_data.xlsx";
paradigms = ["1pulse", "80pps-2pulses", "80pps-4pulses", "80pps-6pulses", "80pps-8pulses"];
response_durations = [0.6, 0.6, 0.6, 0.6, 0.6];
membrane_potential_filters.firdifferentiator.order = 1000;
membrane_potential_filters.firdifferentiator.Fpass = 20;
membrane_potential_filters.firdifferentiator.Fstop = 120;
membrane_potential_filters.firlowpass.order = 1000;
membrane_potential_filters.firlowpass.Fpass = 100;
membrane_potential_filters.firlowpass.Fstop = 120;
membrane_current_filters.firlowpass.order = 1000;
membrane_current_filters.firlowpass.Fpass = 20;
membrane_current_filters.firlowpass.Fstop = 50;
ds = WholeCellRecordingV2(filename, paradigms, response_durations, membrane_potential_filters, membrane_current_filters);
ds = ds.call();
ds = ds.plot_estimations();